pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages{
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/PBust0sN/monolitico-tingeso']])
                bat 'cd monoliticoBackend && mvn clean package'
            }
        }
        stage('Build And Push image to Docker Hub'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'dock', variable: 'DOCKER_TOKEN')]) {
                        bat 'echo %DOCKER_TOKEN% | docker login -u pbust0sn --password-stdin'
                        bat 'cd monoliticoBackend && docker build -t pbust0sn/toolrent-backend:latest .'
                        bat 'docker push pbust0sn/toolrent-backend:latest'
                        bat 'docker logout'
                    }
                }
            }
        }
    }
}